language: generic
os: osx
osx_image: xcode10.1

before_script:
  - brew services restart postgresql

install:
  - brew install shellcheck

script:
  - shellcheck mac -e SC2039 -e SC1117
  - ./mac

matrix:
  fast_finish: true

notifications:
  email: false
