tap 'homebrew/services'
tap 'caskroom/cask'
tap 'caskroom/versions'

# general dependencies
brew 'openssl'
cask 'java' unless system '/usr/libexec/java_home --failfast > /dev/null'

# cli tools
brew 'awscli' # aws command line tools
brew 'awslogs' # view aws cloudwatch logs from CLI
brew 'wget' # super curl
brew 'jq' # command line json processor
brew 'tree' # recursive ls
brew 'zsh' # better shell

# databases, key value stores
brew 'mongodb', restart_service: :changed
brew 'mysql', restart_service: :changed
brew 'postgresql', restart_service: :changed
brew 'redis', restart_service: :changed

# languages
brew 'python'
brew 'pipenv'
brew 'node'
brew 'yarn'
brew 'ruby'

# dev gui
cask 'iterm2' unless File.directory?("/Applications/iTerm.app")
cask 'docker' unless File.directory?("/Applications/Docker.app")
cask 'sublime-text' unless File.directory?("/Applications/Sublime Text.app")
cask 'visual-studio-code' unless File.directory?("/Applications/Visual Studio Code.app.app")

# non-dev gui
cask 'slack' unless File.directory?("/Applications/Slack.app")
cask 'google-chrome-beta' unless File.directory?("/Applications/Google Chrome.app")
cask 'keepingyouawake' unless File.directory?("/Applications/KeepingYouAwake.app")
